[package]
name = "zipfile"
version = "0.1.0"
edition = "2024"

[[bin]]
name = "type"
path = "src/type.rs"

[[bin]]
name = "max"
path = "src/max.rs"

[[bin]]
name = "rd"
path = "src/read.rs"

[[bin]]
name = "te"
path = "src/test_exist.rs"

[dependencies]
zip = "5.1.1"


